version: '3.8'

services:
  backend:
    build: ./backend
    container_name: financial_analyzer_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ./backend
    container_name: financial_analyzer_worker
    command: celery -A app.tasks.worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend

  mongo:
    image: mongo:latest
    container_name: financial_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: financial_redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial_analyzer_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:

